apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f .\docker-compose.yaml -o ./k8s/
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f .\docker-compose.yaml -o ./k8s/
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.network/app: "true"
        io.kompose.service: nginx
    spec:
      containers:
        - image: nginx:1.21.1-alpine
          name: nginx-proxy
          ports:
            - containerPort: 80
            - containerPort: 443
          resources: { }
          volumeMounts:
            - mountPath: /etc/nginx/conf.d
              name: nginx-claim0
              subPath: config
            - mountPath: /secrets
              #              name: nginx-claim1
              name: nginx-claim0
              subPath: secrets
      #              readOnly: true
      restartPolicy: Always
      volumes:
        - name: nginx-claim0
          persistentVolumeClaim:
            claimName: nginx-claim0
#        - name: nginx-claim1
#          persistentVolumeClaim:
#            claimName: nginx-claim1
#            readOnly: true
