apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv-volume0
  labels:
    type: local
    app: nginx
spec:
  #  storageClassName: manual0
  storageClassName: local-storage
  volumeMode: Filesystem
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  #  hostPath:
  #    path: "D:/temp/nginx-reverse-proxy-temp/nginx-ssl-proxy-self-signed-cert-temp/mnt/config"
  #    path: "../mnt/config"
  local:
    path: "D:/temp/nginx-reverse-proxy-temp/nginx-ssl-proxy-self-signed-cert-temp/mnt/config"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: NotIn
              values:
                - xxxx
